apiVersion: eksctl.io/vlalpha5
kind: ClusterConfig
metadata:
  name: roboshop
  region: us-east-1
managedNodeGroups:
  - name: roboshop
    instance Types: ["m5.large", "c3.large", "c4.large", "c3.large"]
    desiredCapacity: 3
    spot: true